# Generated by Django 4.2.3 on 2023-08-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requestLogger", "0002_alter_project_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="date_completed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
